### ISSUE TITLE
Bug running deployment on macOS

### ISSUE THREAD

**Issue by andreped** [andreped/super-ml-pets#31]
Just tested the framework on a macOS Monterey (12.3.1) using Python 3.7.9.
Training works just fine, but deployment crashes.
First time running can also be a bit slow, but that is likely due to macOS running some security checks.
Sudo is also required to run the software, likely due to keyboard library being used. The same was observed on Ubuntu.

Error prompt after running deployment:
```
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    run(ret)
  File "/Users/X/workspace/super-ml-pets/src/deploy_agent.py", line 98, in run
    model = MaskablePPO.load(ret.infer_model, custom_objects=custom_objects)
  File "/Users/X/workspace/super-ml-pets/venv/lib/python3.7/site-packages/stable_baselines3/common/base_class.py", line 705, in load
    path, device=device, custom_objects=custom_objects, print_system_info=print_system_info
  File "/Users/X/workspace/super-ml-pets/venv/lib/python3.7/site-packages/stable_baselines3/common/save_util.py", line 435, in load_from_zip_file
    th_object = th.load(file_content, map_location=device)
  File "/Users/X/workspace/super-ml-pets/venv/lib/python3.7/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/X/workspace/super-ml-pets/venv/lib/python3.7/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x00'.
```

**Comment by andreped** [comment]
There was nothing wrong with deployment on macOS!

When downloading the model from releases, be sure to download a model that was trained in the same python version you are using or older. If model trained in 3.7, using Python >= 3.7. The latest released models were trained on Python 3.8, hence,  Python 3.7 might fail to load these.

Also, when downloading the models (.zip) files, they will be automatically unzipped (macOS aids). This is **bad**. You can disable this by going to the Safari Preferences and disable "Open safe files after downloading".

Also note that the screen resolution on the laptop did not match the expected 1920x1080. But using a different monitor it worked just fine :)
