### ISSUE TITLE
help

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaaaaadd22** [andreped/super-ml-pets#44]
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\GAMEBOT\super-ml-pets-0.0.6\main.py", line 49, in <module>
    run(ret)
  File "C:\Users\Admin\Downloads\GAMEBOT\super-ml-pets-0.0.6\src\deploy_agent.py", line 106, in run
    pets, _ = find_the_animals(
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by aaaaaaaaaaaaaaaaadd22** [comment]
new ver
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\GAMEBOT\super-ml-pets-main\main.py", line 64,
in <module>
    main()
  File "C:\Users\Admin\Downloads\GAMEBOT\super-ml-pets-main\main.py", line 58,
in main
    run(ret)
  File "C:\Users\Admin\Downloads\GAMEBOT\super-ml-pets-main\src\deploy_agent.py", line 127, in run
    " Current Team and Shop \n{}".format(s[action][0]))
TypeError: unhashable type: 'numpy.ndarray'

**Comment by andreped** [comment]
Hello! Did not see this until now, sorry. Did you manage to get further, @aaaaaaaaaaaaaaaaadd22?

**Comment by andreped** [comment]
As far as I can tell this happens due to deployment setup not properly followed (see [here](https://github.com/andreped/super-ml-pets#testing)).

See the very last comment after point 6. After starting the script, you should go into the game (fullscreen) and just let the machine vision system do its thing. If you interrupt the script may fail. We do not have any logic to catch spurious things the user may do. This might be fixed in the future, but is not critical.

I'm closing this issue for now. If you return to the project and have further comments, comment here and I can reopen the issue.
